
main:
  allow-circular-references: true

server:
  servlet:
    context-path: /store

spring:
  datasource:
    url: jdbc:h2:./store
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format-sql: true

  h2:
    console:
      enabled: true
      path: /console
